type: object
properties:
  identifier:
    type: string
    description: Product identifier, i.e. the value of the only `pim_catalog_identifier` attribute
  enabled:
    type: boolean
    description: Whether the product is enable
  family:
    type: string
    description: Family code from which the product inherits its attributes and attributes requirements
  categories:
    type: array
    description: Codes of the categories in which the product is classified
    items:
      type: string
  groups:
    type: array
    description: Codes of the groups to which the product belong
    items:
      type: string
  parent:
    type: string
    description: Code of the parent product model when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.
  values:
    type: object
    description: "Product attributes values, see <a href='/concepts/products.html#focus-on-the-products-values'>Product values</a> section for more details"
    properties:
      attributeCode:
        type: array
        items:
          type: object
          properties:
            scope:
              type: string
              description: Channel code of the product value
            locale:
              type: string
              description: Locale code of the product value
            data:
              type: object
              description: Product value
            linked_data:
              type: object
              description: Object containing labels of attribute options (only available in Serenity and when query parameter "with_attribute_options" is set to "true"). See <a href='/concepts/products.html#the-linked_data-format'>the `linked_data` format</a> section for more details.
              properties:
                attribute:
                  type: string
                code:
                  type: string
                labels:
                  type: object
  associations:
    type: object
    description: Several associations related to groups, product models and/or other products, grouped by association types
    properties:
      associationTypeCode:
        type: object
        properties:
          groups:
            type: array
            description: Array of groups codes with which the product is in relation
            items:
              type: string
          products:
            type: array
            description: Array of product identifiers with which the product is in relation
            items:
              type: string
          product_models:
            type: array
            description: Array of product model codes with which the product is in relation (only available since the v2.1)
            items:
              type: string
  quantified_associations:
    type: object
    description: Several quantified associations related to products and/or product models, grouped by quantified association types (only available in Serenity)
    properties:
      quantifiedAssociationTypeCode:
        type: object
        properties:
          products:
            type: array
            description: Array of objects containing product identifiers and quantities with which the product is in relation
            items:
              type: object
              properties:
                identifier:
                  type: string
                quantity:
                  type: integer
          product_models:
            type: array
            description: Array of objects containing product model codes and quantities with which the product is in relation
            items:
              type: object
              properties:
                code:
                  type: string
                quantity:
                  type: integer
  created:
    type: string
    description: Date of creation
    format: dateTime
  updated:
    type: string
    description: Date of the last update
    format: dateTime
  metadata:
    type: object
    description: More information around the product (only available since the v2.0 in the Enterprise Edition)
    properties:
      workflow_status:
        description: Status of the product regarding the user permissions (only available since the v2.0 in the Enterprise Edition)
        type: string
        enum:
          [
            "read_only",
            "draft_in_progress",
            "proposal_waiting_for_approval",
            "working_copy",
          ]
